#!/usr/bin/node

const ask = require('readline-sync');

let dogBreeds = ["doberman", "pinscher", "golden retriever", "chiuaua", "guiapeca", "pitbull", "poddle", "mini poodle"];
let index;

function getIndex(quest)
{
	while (true) {	/* goto simulation */
			/* (a recursive function is not recommeded on javascript, but it would be more readable) */
		s = ask.question (quest);
		n = Number(s);

		if (s.length == 0) continue;		
		if (!isNaN(n)) break;

		process.stderr.write(`Type a valid number.\n`);
	}

	return n;
}

index = getIndex(`Type a number [0-${dogBreeds.length - 1}] `); 

if (index > dogBreeds.length - 1) {
	process.stderr.write(`Array index out of bounds.\n`);
	process.exit(1); 
} 

console.log(`The choosen dog breed is: ${dogBreeds[index]}.`);
